### ISSUE TITLE
Missing RSS feed on Jeykll based version of hunterdavis.com

### ISSUE THREAD

**Issue by andrewlow** [huntergdavis/huntergdavis.github.io#1]
I finally updated my tt-rss install, which has helpfully stopped hiding "feeds with errors" and hunterdavis is one of them having issues.

I wasn't able to locate a RSS feed on the site anymore, this repo appears to be the source of the site - and no sign of a RSS plugin

https://joelglovier.com/writing/rss-for-jekyll

Doesn't seem hard to support it.. but, this is your site and you get to decide.

Maybe you aren't aware that RSS / Atom is missing - or maybe you don't want to support it. 

I'll leave this up to you. Thanks for sharing!

**Comment by huntergdavis** [comment]
Thank you for bringing this to my attention, and apologies I'm just now seeing your message.  Just updated with support for rss, thanks for the howto link and for reading :)
